language: node_js
os:
  - linux
  - osx
node_js:
  - 'lts/*'
  - '8'
before_install:
  - npm install -g npm@latest
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run lint
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - npm run lh -- --perf=90 --pwa=100 --no-comment https://blog.yuigahama.moe/
branches:
  only:
    - master
    - /^greenkeeper.*$/
